,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas/issues/47032,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47032/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47032/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47032/events,https://github.com/pandas-dev/pandas/pull/47032,1236352230,PR_kwDOAA0YD8431mtS,47032,CI: Start Testing on Python 3.11,"{'login': 'lithomas1', 'id': 47963215, 'node_id': 'MDQ6VXNlcjQ3OTYzMjE1', 'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lithomas1', 'html_url': 'https://github.com/lithomas1', 'followers_url': 'https://api.github.com/users/lithomas1/followers', 'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}', 'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions', 'organizations_url': 'https://api.github.com/users/lithomas1/orgs', 'repos_url': 'https://api.github.com/users/lithomas1/repos', 'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lithomas1/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-05-15T17:51:01Z,2022-05-15T17:57:30Z,,MEMBER,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47032', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47032', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47032.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47032.patch', 'merged_at': None}","- [ ] xref #46680 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47032/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47032/timeline,
1,https://api.github.com/repos/pandas-dev/pandas/issues/47030,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47030/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47030/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47030/events,https://github.com/pandas-dev/pandas/issues/47030,1236274176,I_kwDOAA0YD85JsAwA,47030,DOC: DataFrame.rename Method,"{'login': 'MischaDy', 'id': 44754681, 'node_id': 'MDQ6VXNlcjQ0NzU0Njgx', 'avatar_url': 'https://avatars.githubusercontent.com/u/44754681?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MischaDy', 'html_url': 'https://github.com/MischaDy', 'followers_url': 'https://api.github.com/users/MischaDy/followers', 'following_url': 'https://api.github.com/users/MischaDy/following{/other_user}', 'gists_url': 'https://api.github.com/users/MischaDy/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MischaDy/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MischaDy/subscriptions', 'organizations_url': 'https://api.github.com/users/MischaDy/orgs', 'repos_url': 'https://api.github.com/users/MischaDy/repos', 'events_url': 'https://api.github.com/users/MischaDy/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MischaDy/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 717120670, 'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue', 'name': 'good first issue', 'color': '0e8a16', 'default': True, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 996, 'closed_issues': 843, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-05-16T15:43:21Z', 'due_on': None, 'closed_at': None}",3,2022-05-15T12:26:39Z,2022-05-16T09:40:19Z,,NONE,,,,"### Pandas version checks

- [x] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename



### Documentation problem

The docs for the `inplace` parameter state: ""Whether to return a new `DataFrame`. (...)"". However, it is clear that the boolean has the opposite meaning: If  `inplace=True`, *no* new `DataFrame` will be returned and vice versa.

### Suggested fix for documentation

Something along the lines of: ""Whether not to return a new `DataFrame`. (...)""
Or, perhaps more intuitively: ""Whether to modify the `DataFrame` passed as input. (...)""
Possibly with an enhancing addition: ""Whether to modify the `DataFrame` passed as input, rather than creating a new one.""

These suggestions improve the docs, because the boolean value of `inplace` then corresponds to rather than opposes the actual actions taken by the result. Skimming the docs, one might think that the parameter does the opposite of what the docs say, despite its name. Or, alternatively, one might stumble when reading it, and get the intended meaning afterwards. In any case, it is an unneeded distraction.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47030/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47030/timeline,
2,https://api.github.com/repos/pandas-dev/pandas/issues/47028,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47028/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47028/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47028/events,https://github.com/pandas-dev/pandas/pull/47028,1236240934,PR_kwDOAA0YD8431R2u,47028,Fix: Pandas rolling removes imaginary part of complex,"{'login': 'weikhor', 'id': 36619387, 'node_id': 'MDQ6VXNlcjM2NjE5Mzg3', 'avatar_url': 'https://avatars.githubusercontent.com/u/36619387?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/weikhor', 'html_url': 'https://github.com/weikhor', 'followers_url': 'https://api.github.com/users/weikhor/followers', 'following_url': 'https://api.github.com/users/weikhor/following{/other_user}', 'gists_url': 'https://api.github.com/users/weikhor/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/weikhor/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/weikhor/subscriptions', 'organizations_url': 'https://api.github.com/users/weikhor/orgs', 'repos_url': 'https://api.github.com/users/weikhor/repos', 'events_url': 'https://api.github.com/users/weikhor/events{/privacy}', 'received_events_url': 'https://api.github.com/users/weikhor/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-05-15T09:59:17Z,2022-05-16T17:21:51Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47028', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47028', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47028.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47028.patch', 'merged_at': None}","- [ ] closes #46619
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47028/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47028/timeline,
3,https://api.github.com/repos/pandas-dev/pandas/issues/47026,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47026/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47026/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47026/events,https://github.com/pandas-dev/pandas/pull/47026,1236162331,PR_kwDOAA0YD8431DFk,47026,DOC: Clarify decay argument validation in ewm when times is provided,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 81, 'closed_issues': 764, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-05-16T14:42:35Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",0,2022-05-15T01:48:39Z,2022-05-15T13:58:19Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47026', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47026', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47026.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47026.patch', 'merged_at': None}","- [x] closes #47003 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47026/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47026/timeline,
4,https://api.github.com/repos/pandas-dev/pandas/issues/47025,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47025/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47025/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47025/events,https://github.com/pandas-dev/pandas/pull/47025,1236038652,PR_kwDOAA0YD8430s9W,47025,DEPR: groupby numeric_only default,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'site_admin': False}","[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Deprecate', 'name': 'Deprecate', 'color': '5319e7', 'default': False, 'description': 'Functionality to remove in pandas'}, {'id': 2365523662, 'node_id': 'MDU6TGFiZWwyMzY1NTIzNjYy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Nuisance%20Columns', 'name': 'Nuisance Columns', 'color': '120491', 'default': False, 'description': 'Identifying/Dropping nuisance columns in reductions, groupby.add, DataFrame.apply'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 81, 'closed_issues': 764, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-05-16T14:42:35Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",0,2022-05-14T16:04:46Z,2022-05-15T02:09:07Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47025', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47025', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47025.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47025.patch', 'merged_at': None}","- [x] closes #46072 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

There are two cases we want to emit a deprecation warning for DataFrameGroupBy:
 - numeric_only is not specified and columns get dropped. In this case emit a warning that the default of numeric_only will change to False in the future.
 - numeric_only is specified to False and columns still get dropped. In this case emit a warning that the op will raise in the future.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47025/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47025/timeline,
5,https://api.github.com/repos/pandas-dev/pandas/issues/47024,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47024/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47024/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47024/events,https://github.com/pandas-dev/pandas/issues/47024,1236021807,I_kwDOAA0YD85JrDIv,47024,BUG: read_csv not guessing delimiter,"{'login': 'Gabriel-p', 'id': 6054951, 'node_id': 'MDQ6VXNlcjYwNTQ5NTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6054951?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Gabriel-p', 'html_url': 'https://github.com/Gabriel-p', 'followers_url': 'https://api.github.com/users/Gabriel-p/followers', 'following_url': 'https://api.github.com/users/Gabriel-p/following{/other_user}', 'gists_url': 'https://api.github.com/users/Gabriel-p/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Gabriel-p/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Gabriel-p/subscriptions', 'organizations_url': 'https://api.github.com/users/Gabriel-p/orgs', 'repos_url': 'https://api.github.com/users/Gabriel-p/repos', 'events_url': 'https://api.github.com/users/Gabriel-p/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Gabriel-p/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 996, 'closed_issues': 843, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-05-16T15:43:21Z', 'due_on': None, 'closed_at': None}",3,2022-05-14T14:52:23Z,2022-05-16T15:43:21Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
file = ""pandas_test.dat""

# Fails
df = pd.read_csv(file, delimiter=None)

# Works
from astropy.io import ascii
df = ascii.read(file)
```


### Issue Description

`pandas` fails when trying to guess the delimiter (space) in the test file. `astropy` on the other hand is able to guess it correctly

The test file is here [pandas_test.dat.zip](https://github.com/pandas-dev/pandas/files/8693182/pandas_test.dat.zip)


### Expected Behavior

The delimiter should be correctly guessed

### Installed Versions

<details>

```
pd.__version__
'1.4.2'
```

</details>


The line `pd.show_versions()` throws the following error:

```
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/pandas/util/_print_versions.py"", line 109, in show_versions
    deps = _get_dependency_info()
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/pandas/util/_print_versions.py"", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors=""ignore"")
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/pandas/compat/_optional.py"", line 138, in import_optional_dependency
    module = importlib.import_module(name)
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/importlib/__init__.py"", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File ""<frozen importlib._bootstrap>"", line 1030, in _gcd_import
  File ""<frozen importlib._bootstrap>"", line 1007, in _find_and_load
  File ""<frozen importlib._bootstrap>"", line 986, in _find_and_load_unlocked
  File ""<frozen importlib._bootstrap>"", line 680, in _load_unlocked
  File ""<frozen importlib._bootstrap_external>"", line 850, in exec_module
  File ""<frozen importlib._bootstrap>"", line 228, in _call_with_frames_removed
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/setuptools/__init__.py"", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/_distutils_hack/override.py"", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/_distutils_hack/__init__.py"", line 72, in do_override
    ensure_local_distutils()
  File ""/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/_distutils_hack/__init__.py"", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /home/gabriel/miniconda3/envs/asteca/lib/python3.9/distutils/core.py
```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47024/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47024/timeline,
6,https://api.github.com/repos/pandas-dev/pandas/issues/47023,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47023/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47023/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47023/events,https://github.com/pandas-dev/pandas/issues/47023,1235972506,I_kwDOAA0YD85Jq3Ga,47023,ASV Bug ? After commit 009c4c62.,"{'login': 'smarie', 'id': 3236794, 'node_id': 'MDQ6VXNlcjMyMzY3OTQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3236794?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/smarie', 'html_url': 'https://github.com/smarie', 'followers_url': 'https://api.github.com/users/smarie/followers', 'following_url': 'https://api.github.com/users/smarie/following{/other_user}', 'gists_url': 'https://api.github.com/users/smarie/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/smarie/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/smarie/subscriptions', 'organizations_url': 'https://api.github.com/users/smarie/orgs', 'repos_url': 'https://api.github.com/users/smarie/repos', 'events_url': 'https://api.github.com/users/smarie/events{/privacy}', 'received_events_url': 'https://api.github.com/users/smarie/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI3NzU5MTI=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Benchmark', 'name': 'Benchmark', 'color': 'ae68cc', 'default': False, 'description': 'Performance (ASV) benchmarks'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-05-14T13:19:35Z,2022-05-15T09:26:09Z,,CONTRIBUTOR,,,,"It seems that commit 009c4c62 (fix in the `to_json` function) introduced some compilation problem on windows, that ASV does not like. Note that manual compilation seems to still work fine, so this is maybe related to the ASV config ?

```python
> asv run d5cf2b86

""C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe"" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\_dev\pyt
hon_ws\_Libs_OpenSource\pandas\asv_bench\env\45e7123d25d88e958f183355b52ee854\libs /LIBPATH:C:\_dev\python_ws\_Libs_OpenSource\pandas\asv_bench\env\45e7123d25d88e958f183355b52ee854 /LIBPATH:C:\_dev\python_ws\_Li
bs_OpenSource\pandas\asv_bench\env\45e7123d25d88e958f183355b52ee854\PCbuild\amd64 ""/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64"" ""/LIBPATH:C:\Program 
Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64"" ""/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64"" ""/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\
MSVC\14.16.27023\lib\x64"" ""/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64"" ""/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64"" ""/LIBPATH:C:\Program Files (x86)\Mi
crosoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64"" ""/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64"" ""/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.1776
3.0\um\x64"" ""/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64"" ""/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64"" ""/LIBPATH:C:\Pr
ogram Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64"" /EXPORT:PyInit_json build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujson/lib/ultrajsondec.obj build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujson
/lib/ultrajsonenc.obj build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujson/python/JSONtoObj.obj build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujson/python/date_conversions.obj build\temp.win-amd64-3.8\Rel
ease\pandas/_libs/src/ujson/python/objToJSON.obj build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujson/python/ujson.obj build\temp.win-amd64-3.8\Release\pandas/_libs/tslibs/src/datetime/np_datetime.obj build\t
emp.win-amd64-3.8\Release\pandas/_libs/tslibs/src/datetime/np_datetime_strings.obj /OUT:build\lib.win-amd64-3.8\pandas\_libs\json.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujso
n/lib\json.cp38-win_amd64.lib
      Cr�ation de la biblioth�que build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujson/lib\json.cp38-win_amd64.lib et de l'objet build\temp.win-amd64-3.8\Release\pandas/_libs/src/ujson/lib\json.cp38-win_amd64
.exp
   G�n�ration de code en cours
   Fin de la g�n�ration du code
   Fin de la g�n�ration du code
   STDERR -------->
   no previously-included directories found matching 'doc\build'
   warning: no previously-included files matching '*.so' found anywhere in distribution
   warning: no previously-included files matching '*~' found anywhere in distribution
   warning: no previously-included files matching '.DS_Store' found anywhere in distribution
   warning: no previously-included files matching '#*' found anywhere in distribution
   warning: no previously-included files matching '*.py[ocd]' found anywhere in distribution
   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe' failed with exit code 1
```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47023/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47023/timeline,
7,https://api.github.com/repos/pandas-dev/pandas/issues/47022,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47022/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47022/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47022/events,https://github.com/pandas-dev/pandas/pull/47022,1235964479,PR_kwDOAA0YD8430kUa,47022,DOC: Fix some typos in pandas/.,"{'login': 'Yulv-git', 'id': 34329208, 'node_id': 'MDQ6VXNlcjM0MzI5MjA4', 'avatar_url': 'https://avatars.githubusercontent.com/u/34329208?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Yulv-git', 'html_url': 'https://github.com/Yulv-git', 'followers_url': 'https://api.github.com/users/Yulv-git/followers', 'following_url': 'https://api.github.com/users/Yulv-git/following{/other_user}', 'gists_url': 'https://api.github.com/users/Yulv-git/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Yulv-git/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Yulv-git/subscriptions', 'organizations_url': 'https://api.github.com/users/Yulv-git/orgs', 'repos_url': 'https://api.github.com/users/Yulv-git/repos', 'events_url': 'https://api.github.com/users/Yulv-git/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Yulv-git/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 81, 'closed_issues': 764, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-05-16T14:42:35Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",2,2022-05-14T12:40:39Z,2022-05-15T04:37:47Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47022', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47022', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47022.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47022.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47022/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47022/timeline,
8,https://api.github.com/repos/pandas-dev/pandas/issues/47018,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47018/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47018/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47018/events,https://github.com/pandas-dev/pandas/pull/47018,1235700810,PR_kwDOAA0YD843zvr_,47018,REF: merge datetime_to_datetime64 into array_to_datetime,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2ODE=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Refactor', 'name': 'Refactor', 'color': 'FCE94F', 'default': False, 'description': 'Internal refactoring of code'}, {'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4NDA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries', 'name': 'Timeseries', 'color': 'AFEEEE', 'default': False, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 81, 'closed_issues': 764, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-05-16T14:42:35Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",2,2022-05-13T20:51:26Z,2022-05-15T23:26:44Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47018', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47018', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47018.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47018.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47018/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47018/timeline,
9,https://api.github.com/repos/pandas-dev/pandas/issues/47014,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47014/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47014/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47014/events,https://github.com/pandas-dev/pandas/issues/47014,1235440194,I_kwDOAA0YD85Jo1JC,47014,ENH: implement DateOffset + datetime64 array,"{'login': 'hottwaj', 'id': 5629061, 'node_id': 'MDQ6VXNlcjU2MjkwNjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5629061?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/hottwaj', 'html_url': 'https://github.com/hottwaj', 'followers_url': 'https://api.github.com/users/hottwaj/followers', 'following_url': 'https://api.github.com/users/hottwaj/following{/other_user}', 'gists_url': 'https://api.github.com/users/hottwaj/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/hottwaj/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/hottwaj/subscriptions', 'organizations_url': 'https://api.github.com/users/hottwaj/orgs', 'repos_url': 'https://api.github.com/users/hottwaj/repos', 'events_url': 'https://api.github.com/users/hottwaj/events{/privacy}', 'received_events_url': 'https://api.github.com/users/hottwaj/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2NTEwNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Compat', 'name': 'Compat', 'color': '0052cc', 'default': False, 'description': 'pandas objects compatability with Numpy or Python functions'}]",open,False,,[],,1,2022-05-13T16:15:40Z,2022-05-16T10:25:43Z,,NONE,,,,"#### Is your feature request related to a problem?

DateOffset + a numpy array of type datetime64 does not work, see examples at the end of this post

#### Describe the solution you'd like

can `__add__` or `__radd__` of DateOffset be changed to implement addition to datetime64 array?

#### API breaking implications

I am not the right person to comment, but seems unlikely to have an impact on existing API if it can be done at all

#### Describe alternatives you've considered

Sorry, not thought of alternatives so far

#### Code example

```python
>>> import pandas
>>> import numpy
>>> dates = pandas.Series([pandas.Timestamp(2021, 1, 1) + pandas.Timedelta(days=d) for d in range(1000)])
>>> offset = pandas.offsets.MonthEnd()

>>> # adding a pandas Timestamp series to an offset obviously works
>>> dates + offset
0     2021-01-31
1     2021-01-31
         ...    
998   2023-09-30
999   2023-09-30
Length: 1000, dtype: datetime64[ns]

>>> # adding the underlying numpy datetime64 values does not work 
>>> offset + dates.values
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
----> 1 offset + dates.values

UFuncTypeError: ufunc 'add' cannot use operands with types dtype('O') and dtype('<M8[ns]')

>>> # slightly different error if we swap the order of the two variables
>>> dates.values + offset
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
----> 1 dates.values + offset

TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations.

>>> # the desired result can be achieved by using DateOffset._apply_array() and casting to M8[ns]
>>> offset._apply_array(dates.values).astype('M8[ns]')
array(['2021-01-31T00:00:00.000000000', '2021-01-31T00:00:00.000000000',
       '2021-01-31T00:00:00.000000000', '2021-01-31T00:00:00.000000000',
       '2021-01-31T00:00:00.000000000', '2021-01-31T00:00:00.000000000',
       '2021-01-31T00:00:00.000000000', '2021-01-31T00:00:00.000000000',
       etc])
```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47014/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47014/timeline,
10,https://api.github.com/repos/pandas-dev/pandas/issues/47011,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47011/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47011/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47011/events,https://github.com/pandas-dev/pandas/issues/47011,1234722776,I_kwDOAA0YD85JmF_Y,47011,BUG: pandas accepts non-increasing MultiIndex header arguments,"{'login': 'ahawryluk', 'id': 50434302, 'node_id': 'MDQ6VXNlcjUwNDM0MzAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/50434302?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ahawryluk', 'html_url': 'https://github.com/ahawryluk', 'followers_url': 'https://api.github.com/users/ahawryluk/followers', 'following_url': 'https://api.github.com/users/ahawryluk/following{/other_user}', 'gists_url': 'https://api.github.com/users/ahawryluk/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ahawryluk/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ahawryluk/subscriptions', 'organizations_url': 'https://api.github.com/users/ahawryluk/orgs', 'repos_url': 'https://api.github.com/users/ahawryluk/repos', 'events_url': 'https://api.github.com/users/ahawryluk/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ahawryluk/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}, {'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}]",open,False,"{'login': 'ahawryluk', 'id': 50434302, 'node_id': 'MDQ6VXNlcjUwNDM0MzAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/50434302?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ahawryluk', 'html_url': 'https://github.com/ahawryluk', 'followers_url': 'https://api.github.com/users/ahawryluk/followers', 'following_url': 'https://api.github.com/users/ahawryluk/following{/other_user}', 'gists_url': 'https://api.github.com/users/ahawryluk/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ahawryluk/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ahawryluk/subscriptions', 'organizations_url': 'https://api.github.com/users/ahawryluk/orgs', 'repos_url': 'https://api.github.com/users/ahawryluk/repos', 'events_url': 'https://api.github.com/users/ahawryluk/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ahawryluk/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'ahawryluk', 'id': 50434302, 'node_id': 'MDQ6VXNlcjUwNDM0MzAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/50434302?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ahawryluk', 'html_url': 'https://github.com/ahawryluk', 'followers_url': 'https://api.github.com/users/ahawryluk/followers', 'following_url': 'https://api.github.com/users/ahawryluk/following{/other_user}', 'gists_url': 'https://api.github.com/users/ahawryluk/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ahawryluk/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ahawryluk/subscriptions', 'organizations_url': 'https://api.github.com/users/ahawryluk/orgs', 'repos_url': 'https://api.github.com/users/ahawryluk/repos', 'events_url': 'https://api.github.com/users/ahawryluk/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ahawryluk/received_events', 'type': 'User', 'site_admin': False}]","{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 996, 'closed_issues': 843, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-05-16T15:43:21Z', 'due_on': None, 'closed_at': None}",2,2022-05-13T04:23:09Z,2022-05-16T03:49:04Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
from io import StringIO
import pandas as pd

data = """"""a,a,a,b,c,c
q,r,s,t,u,v
1,2,3,4,5,6
7,8,9,10,11,12""""""
pd.read_csv(StringIO(data), header=[1, 0])
```


### Issue Description

pandas accepts non-increasing MultiIndex header arguments, but they don't work. For instance, the snippet above produces

```
  NaN                    
    a a.1 a.2   b   c c.1
0   a   a   a   b   c   c
1   q   r   s   t   u   v
2   1   2   3   4   5   6
3   7   8   9  10  11  12
```

i.e., a DataFrame whose columns are

```
MultiIndex([(nan,   'a'),
            (nan, 'a.1'),
            (nan, 'a.2'),
            (nan,   'b'),
            (nan,   'c'),
            (nan, 'c.1')],
           )
```

Parsing the data with header=[0, 0] is also accepted, and behaves sensibly:

```
   a           b   c    
   a a.1 a.2   b   c c.1
0  q   r   s   t   u   v
1  1   2   3   4   5   6
2  7   8   9  10  11  12
```
but I can't see a reason to support redundant header levels.

### Expected Behavior

I propose that non-increasing header arguments raise a ValueError('header elements must be increasing') or something to that effect.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 7c913d6b750f5fe0f3679dc66441011aa90158f6
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-27-generic
Version          : #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_CA.UTF-8
LOCALE           : en_CA.UTF-8

pandas           : 1.5.0.dev0+786.g7c913d6b75
numpy            : 1.21.5
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.0.0
Cython           : 0.29.28
pytest           : 7.1.1
hypothesis       : 6.41.0
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.0
bottleneck       : 1.3.4
brotli           : 
fastparquet      : 0.8.0
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : 1.1.4
pyxlsb           : 1.0.9
s3fs             : 2021.11.0
scipy            : 1.8.0
snappy           : 
sqlalchemy       : 1.4.35
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47011/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47011/timeline,
11,https://api.github.com/repos/pandas-dev/pandas/issues/47010,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47010/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47010/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47010/events,https://github.com/pandas-dev/pandas/pull/47010,1234539522,PR_kwDOAA0YD843v9oW,47010,TYP: resolve mypy ingores in core/indexing.py,"{'login': 'iasoon', 'id': 6320308, 'node_id': 'MDQ6VXNlcjYzMjAzMDg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6320308?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/iasoon', 'html_url': 'https://github.com/iasoon', 'followers_url': 'https://api.github.com/users/iasoon/followers', 'following_url': 'https://api.github.com/users/iasoon/following{/other_user}', 'gists_url': 'https://api.github.com/users/iasoon/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/iasoon/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/iasoon/subscriptions', 'organizations_url': 'https://api.github.com/users/iasoon/orgs', 'repos_url': 'https://api.github.com/users/iasoon/repos', 'events_url': 'https://api.github.com/users/iasoon/events{/privacy}', 'received_events_url': 'https://api.github.com/users/iasoon/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-05-12T22:25:21Z,2022-05-16T14:48:33Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47010', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47010', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47010.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47010.patch', 'merged_at': None}","xref https://github.com/pandas-dev/pandas/issues/37715

Notes: `axis` has to be passed as an argument to `_tupleize_axis_indexer` in order to assert that it is not `None`. Since this kind of decouples it from the `_LocationIndexer` class, I made it a standalone utility function.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47010/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47010/timeline,
12,https://api.github.com/repos/pandas-dev/pandas/issues/47009,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47009/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47009/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47009/events,https://github.com/pandas-dev/pandas/issues/47009,1234343849,I_kwDOAA0YD85Jkpep,47009,BUG: sort_index cause UnicodeDecodeError in non utf-8 locales,"{'login': 'zdenop', 'id': 574156, 'node_id': 'MDQ6VXNlcjU3NDE1Ng==', 'avatar_url': 'https://avatars.githubusercontent.com/u/574156?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zdenop', 'html_url': 'https://github.com/zdenop', 'followers_url': 'https://api.github.com/users/zdenop/followers', 'following_url': 'https://api.github.com/users/zdenop/following{/other_user}', 'gists_url': 'https://api.github.com/users/zdenop/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zdenop/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zdenop/subscriptions', 'organizations_url': 'https://api.github.com/users/zdenop/orgs', 'repos_url': 'https://api.github.com/users/zdenop/repos', 'events_url': 'https://api.github.com/users/zdenop/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zdenop/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzMzI4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Visualization', 'name': 'Visualization', 'color': '8AE234', 'default': False, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 996, 'closed_issues': 843, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-05-16T15:43:21Z', 'due_on': None, 'closed_at': None}",3,2022-05-12T18:32:26Z,2022-05-15T15:42:01Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import locale

locale.setlocale(locale.LC_ALL, ""sk_SK"")

data = {
        ""A"": {
            ""2022-05-11"": 81.72,
            ""2022-05-10"": 79.69,
            ""2022-05-09"": 80.89,
            ""2022-05-06"": 80.57,
        },
        ""B"": {
            ""2022-05-11"": 52.85,
            ""2022-05-10"": 50.28,
            ""2022-05-09"": 55.71,
            ""2022-05-06"": 51.96,
        },
        ""C"": {
            ""2022-05-11"": 84.87,
            ""2022-05-10"": 83.08,
            ""2022-05-09"": 84.25,
            ""2022-05-06"": 83.99,
        },
        ""D"": {
            ""2022-05-11"": 80.07,
            ""2022-05-10"": 76.98,
            ""2022-05-09"": 77.66,
            ""2022-05-06"": 78.07,
        },
    }

dfp = pd.DataFrame.from_dict(data)
dfp.index = pd.to_datetime(dfp.index)
dfp.sort_index(ascending=True).plot()
```


### Issue Description

plot function cause error:

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
File C:\Python\Python39\lib\site-packages\IPython\core\formatters.py:339, in BaseFormatter.__call__(self, obj)
    337     pass
    338 else:
--> 339     return printer(obj)
    340 # Finally look for special method names
    341 method = get_real_method(obj, self.print_method)

File C:\Python\Python39\lib\site-packages\IPython\core\pylabtools.py:151, in print_figure(fig, fmt, bbox_inches, base64, **kwargs)
    148     from matplotlib.backend_bases import FigureCanvasBase
    149     FigureCanvasBase(fig)
--> 151 fig.canvas.print_figure(bytes_io, **kw)
    152 data = bytes_io.getvalue()
    153 if fmt == 'svg':

File C:\Python\Python39\lib\site-packages\matplotlib\backend_bases.py:2295, in FigureCanvasBase.print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2289     renderer = _get_renderer(
   2290         self.figure,
   2291         functools.partial(
   2292             print_method, orientation=orientation)
   2293     )
   2294     with getattr(renderer, ""_draw_disabled"", nullcontext)():
-> 2295         self.figure.draw(renderer)
   2297 if bbox_inches:
   2298     if bbox_inches == ""tight"":

File C:\Python\Python39\lib\site-packages\matplotlib\artist.py:73, in _finalize_rasterization.<locals>.draw_wrapper(artist, renderer, *args, **kwargs)
     71 @wraps(draw)
     72 def draw_wrapper(artist, renderer, *args, **kwargs):
---> 73     result = draw(artist, renderer, *args, **kwargs)
     74     if renderer._rasterizing:
     75         renderer.stop_rasterizing()

File C:\Python\Python39\lib\site-packages\matplotlib\artist.py:50, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     47     if artist.get_agg_filter() is not None:
     48         renderer.start_filter()
---> 50     return draw(artist, renderer)
     51 finally:
     52     if artist.get_agg_filter() is not None:

File C:\Python\Python39\lib\site-packages\matplotlib\figure.py:2837, in Figure.draw(self, renderer)
   2834         # ValueError can occur when resizing a window.
   2836 self.patch.draw(renderer)
-> 2837 mimage._draw_list_compositing_images(
   2838     renderer, self, artists, self.suppressComposite)
   2840 for sfig in self.subfigs:
   2841     sfig.draw(renderer)

File C:\Python\Python39\lib\site-packages\matplotlib\image.py:132, in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130 if not_composite or not has_images:
    131     for a in artists:
--> 132         a.draw(renderer)
    133 else:
    134     # Composite any adjacent images together
    135     image_group = []

File C:\Python\Python39\lib\site-packages\matplotlib\artist.py:50, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     47     if artist.get_agg_filter() is not None:
     48         renderer.start_filter()
---> 50     return draw(artist, renderer)
     51 finally:
     52     if artist.get_agg_filter() is not None:

File C:\Python\Python39\lib\site-packages\matplotlib\axes\_base.py:3091, in _AxesBase.draw(self, renderer)
   3088         a.draw(renderer)
   3089     renderer.stop_rasterizing()
-> 3091 mimage._draw_list_compositing_images(
   3092     renderer, self, artists, self.figure.suppressComposite)
   3094 renderer.close_group('axes')
   3095 self.stale = False

File C:\Python\Python39\lib\site-packages\matplotlib\image.py:132, in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130 if not_composite or not has_images:
    131     for a in artists:
--> 132         a.draw(renderer)
    133 else:
    134     # Composite any adjacent images together
    135     image_group = []

File C:\Python\Python39\lib\site-packages\matplotlib\artist.py:50, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     47     if artist.get_agg_filter() is not None:
     48         renderer.start_filter()
---> 50     return draw(artist, renderer)
     51 finally:
     52     if artist.get_agg_filter() is not None:

File C:\Python\Python39\lib\site-packages\matplotlib\axis.py:1158, in Axis.draw(self, renderer, *args, **kwargs)
   1155     return
   1156 renderer.open_group(__name__, gid=self.get_gid())
-> 1158 ticks_to_draw = self._update_ticks()
   1159 ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1160                                                         renderer)
   1162 for tick in ticks_to_draw:

File C:\Python\Python39\lib\site-packages\matplotlib\axis.py:1046, in Axis._update_ticks(self)
   1041 """"""
   1042 Update ticks (position and labels) using the current data interval of
   1043 the axes.  Return the list of ticks that will be drawn.
   1044 """"""
   1045 major_locs = self.get_majorticklocs()
-> 1046 major_labels = self.major.formatter.format_ticks(major_locs)
   1047 major_ticks = self.get_major_ticks(len(major_locs))
   1048 self.major.formatter.set_locs(major_locs)

File C:\Python\Python39\lib\site-packages\matplotlib\ticker.py:224, in Formatter.format_ticks(self, values)
    222 """"""Return the tick labels for all the ticks at once.""""""
    223 self.set_locs(values)
--> 224 return [self(value, i) for i, value in enumerate(values)]

File C:\Python\Python39\lib\site-packages\matplotlib\ticker.py:224, in <listcomp>(.0)
    222 """"""Return the tick labels for all the ticks at once.""""""
    223 self.set_locs(values)
--> 224 return [self(value, i) for i, value in enumerate(values)]

File C:\Python\Python39\lib\site-packages\pandas\plotting\_matplotlib\converter.py:1074, in TimeSeries_DateFormatter.__call__(self, x, pos)
   1072 if isinstance(fmt, np.bytes_):
   1073     fmt = fmt.decode(""utf-8"")
-> 1074 return Period(ordinal=int(x), freq=self.freq).strftime(fmt)

File C:\Python\Python39\lib\site-packages\pandas\_libs\tslibs\period.pyx:2458, in pandas._libs.tslibs.period._Period.strftime()

File C:\Python\Python39\lib\site-packages\pandas\_libs\tslibs\period.pyx:1225, in pandas._libs.tslibs.period.period_format()

File C:\Python\Python39\lib\site-packages\pandas\_libs\tslibs\period.pyx:1258, in pandas._libs.tslibs.period._period_strftime()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 4: invalid continuation byte
```



### Expected Behavior

However I found out that:

-  `dfp.sort_index(ascending=False).plot()` works ok.
- `locale.setlocale(locale.LC_ALL, ""de_DE"")` work ok.

I expect that the plot function works regardless of used in locale or sorting.

### Installed Versions

<details>

NSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : sk_SK.ISO8859-2

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.1
setuptools       : 51.3.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.6.4
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.2
jinja2           : 3.1.1
IPython          : 8.0.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 5.0.0
pyreadstat       : None
pyxlsb           : 1.0.9
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.4.28
tables           : None
tabulate         : 0.8.9
xarray           : 0.20.1
xlrd             : 1.2.0
xlwt             : 1.3.0
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47009/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47009/timeline,
13,https://api.github.com/repos/pandas-dev/pandas/issues/47006,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47006/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47006/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47006/events,https://github.com/pandas-dev/pandas/issues/47006,1233693416,I_kwDOAA0YD85JiKro,47006,"BUG: dataframe with datetimeindex as index, when indexing columns interprets some strings as datetimes","{'login': 'JamesHowse', 'id': 40427038, 'node_id': 'MDQ6VXNlcjQwNDI3MDM4', 'avatar_url': 'https://avatars.githubusercontent.com/u/40427038?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JamesHowse', 'html_url': 'https://github.com/JamesHowse', 'followers_url': 'https://api.github.com/users/JamesHowse/followers', 'following_url': 'https://api.github.com/users/JamesHowse/following{/other_user}', 'gists_url': 'https://api.github.com/users/JamesHowse/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JamesHowse/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JamesHowse/subscriptions', 'organizations_url': 'https://api.github.com/users/JamesHowse/orgs', 'repos_url': 'https://api.github.com/users/JamesHowse/repos', 'events_url': 'https://api.github.com/users/JamesHowse/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JamesHowse/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4NDA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries', 'name': 'Timeseries', 'color': 'AFEEEE', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-05-12T09:12:00Z,2022-05-16T13:31:24Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
index = pd.DatetimeIndex([pd.to_datetime(""2035-01-01 01:00:00""), pd.to_datetime(""2036-01-01 00:00:00"")])
df = pd.DataFrame(index=index)
df.loc[:, ""110735""] = 0
print(df)
```


### Issue Description

Under certain situations assignment is broken
* Dataframe has a DatetimeIndex as its index.
* You want to assign to an entire column (either with .loc or directly with [ ])
* The column name you want to assign is a string which can be interpreted as a datetime within the range of datetime values in the datetimeindex. In the example above ""110735"" is interpreted as 2035-11-07.

If these conditions are met, the assignment fails and the column is not populated. Pandas is interpreting the string as a datetime and seems to think you are attempting to access the row ""110735"". 

In recent versions a warning is produced, but the script does not crash. This warning indicates that pandas thinks we have tried to use indexing like `frame[string]`, however we have used `frame.loc[:, string]` which should not have this issue.
This FutureWarning is not valid as the assignment fails completely and no changes are made to the dataframe.
> FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  self.obj[key] = value
  
In recent versions if you run with ""df.loc[df.index, ""110735""] = 0"" you get a crash with this error:
> pandas/core/indexing.py:1684: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  self.obj[key] = infer_fill_value(value)
Traceback (most recent call last):
  File ""/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py"", line 3361, in get_loc
return self._engine.get_loc(casted_key)
  File ""pandas/_libs/index.pyx"", line 76, in pandas._libs.index.IndexEngine.get_loc
  File ""pandas/_libs/index.pyx"", line 108, in pandas._libs.index.IndexEngine.get_loc
  File ""pandas/_libs/hashtable_class_helper.pxi"", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File ""pandas/_libs/hashtable_class_helper.pxi"", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '110735'

In older pandas versions it crashes with a KeyError when ""df.loc[:, ""110735""] = 0"" is run :

> Traceback (most recent call last):
  File ""base.py"", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File ""pandas\_libs\index.pyx"", line 70, in pandas._libs.index.IndexEngine.get_loc
  File ""pandas\_libs\index.pyx"", line 101, in pandas._libs.index.IndexEngine.get_loc
  File ""pandas\_libs\hashtable_class_helper.pxi"", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File ""pandas\_libs\hashtable_class_helper.pxi"", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '110735'

### Expected Behavior

Expected behaviour is that a column ""110735"" is populated with 0 in all rows. 

### Installed Versions

Remote test with a more recent pandas version:
<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-1017-aws
Version          : #19~20.04.1-Ubuntu SMP Mon Mar 7 12:53:12 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.1.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
None
</details>

Local test with an older pandas version:
<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.1.5
numpy            : 1.19.1
pytz             : 2018.6
dateutil         : 2.7.3
pip              : 21.3.1
setuptools       : 40.4.3
Cython           : 0.29
pytest           : 6.1.1
hypothesis       : 3.79.3
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.2
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.3.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : None
fsspec           : 2022.01.0
fastparquet      : 0.8.0
gcsfs            : None
matplotlib       : 3.0.0
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : 1.4.21
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : None
</details>","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47006/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47006/timeline,
14,https://api.github.com/repos/pandas-dev/pandas/issues/47005,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47005/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47005/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47005/events,https://github.com/pandas-dev/pandas/issues/47005,1233657909,I_kwDOAA0YD85JiCA1,47005,BUG: PeriodIndex looses tz information,"{'login': 'joooeey', 'id': 28426758, 'node_id': 'MDQ6VXNlcjI4NDI2NzU4', 'avatar_url': 'https://avatars.githubusercontent.com/u/28426758?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/joooeey', 'html_url': 'https://github.com/joooeey', 'followers_url': 'https://api.github.com/users/joooeey/followers', 'following_url': 'https://api.github.com/users/joooeey/following{/other_user}', 'gists_url': 'https://api.github.com/users/joooeey/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/joooeey/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/joooeey/subscriptions', 'organizations_url': 'https://api.github.com/users/joooeey/orgs', 'repos_url': 'https://api.github.com/users/joooeey/repos', 'events_url': 'https://api.github.com/users/joooeey/events{/privacy}', 'received_events_url': 'https://api.github.com/users/joooeey/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 60458168, 'node_id': 'MDU6TGFiZWw2MDQ1ODE2OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timezones', 'name': 'Timezones', 'color': '5319e7', 'default': False, 'description': 'Timezone data dtype'}, {'id': 60635328, 'node_id': 'MDU6TGFiZWw2MDYzNTMyOA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Period', 'name': 'Period', 'color': 'eb6420', 'default': False, 'description': 'Period data type'}, {'id': 1628184320, 'node_id': 'MDU6TGFiZWwxNjI4MTg0MzIw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Warnings', 'name': 'Warnings', 'color': 'f2f074', 'default': False, 'description': 'Warnings that appear or should be added to pandas'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-05-12T08:49:16Z,2022-05-12T10:08:45Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

pd.period_range(""2022-01-01 06:00:00+02:00"", ""2022-01-01 09:00:00+02:00"", freq=""H"")

Out[17]: 
PeriodIndex(['2022-01-01 06:00', '2022-01-01 07:00', '2022-01-01 08:00',
             '2022-01-01 09:00'],
            dtype='period[H]')
```


### Issue Description

Creating a `PeriodIndex `with `pd.period_range` with timezone-aware inputs creates a timezone-naive `PeriodIndex` without even emmitting a warning that the timezone is dropped.

This appears to have the same root cause as #28039 and #21333. There is a fix for #21333 in #22549 (i.e. we warn now) but to me that seems too far upstream. This needs to be fixed in the `PeriodIndex` constructor.

### Expected Behavior

**The good option, analogous to `DatetimeIndex`:**
- Whenever a `PeriodIndex` is created with all arguments in the same time-zone like in the example above, the resulting `PeriodIndex` acquires that time zone.
- If all arguments are time-zone naive, the `PeriodIndex` will be time-zone naive too.
- If different time-zones are mixed, an error is raised.
- If time-zone aware and naive objects are mixed, an error is raised.
**The lazy option, which I consider urgent to implement:**
Whenever a `PeriodIndex` is created with at least one time-zone aware argument, a warning is raised saying that the result will be time-zone naive. This is crucial to avoid bugs.
**Note**
Whatever solution we go with, this should be fixed in the constructor of `PeriodIndex` not further up in `pd.period_range`, `Timestamp.to_period` or similar.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-97-generic
Version          : #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.19.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.18.2
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47005/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47005/timeline,
15,https://api.github.com/repos/pandas-dev/pandas/issues/47004,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47004/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47004/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47004/events,https://github.com/pandas-dev/pandas/pull/47004,1233143321,PR_kwDOAA0YD843rW2V,47004,"Simplify Timedelta init, standardize overflow errors","{'login': 'patrickmckenna', 'id': 3589536, 'node_id': 'MDQ6VXNlcjM1ODk1MzY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3589536?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickmckenna', 'html_url': 'https://github.com/patrickmckenna', 'followers_url': 'https://api.github.com/users/patrickmckenna/followers', 'following_url': 'https://api.github.com/users/patrickmckenna/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickmckenna/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickmckenna/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickmckenna/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickmckenna/orgs', 'repos_url': 'https://api.github.com/users/patrickmckenna/repos', 'events_url': 'https://api.github.com/users/patrickmckenna/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickmckenna/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,3,2022-05-11T20:22:31Z,2022-05-16T17:27:01Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47004', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47004', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47004.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47004.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Per https://github.com/pandas-dev/pandas/pull/46936#issuecomment-1122981776, this PR extracts the functional updates in #46936, to simplify review. The main motivations are those explained in https://github.com/pandas-dev/pandas/pull/46936#discussion_r869761730:

> - DRY up `Timedelta` creation logic, which was divided and duplicated over several functions
> - Do so outside `Timdelta.__new__`, since (AFAICT) there shouldn't yet be a public API for creating instances with non-nano resolution
> - Add overflow checks, and consistently raise `OutOfBoundsTimedelta` when it's detected.

As a bonus, this appears to speed things up considerably, especially in the case of passing `int`s (by avoiding the unnecessary `int -> td64[ns] -> int` conversion):

```
       before           after         ratio
     [a853022e]       [d4444404]
     <main>           <td-construction>
-      8.41±0.8μs       7.50±0.2μs     0.89  tslibs.timedelta.TimedeltaConstructor.time_from_unit
-      7.99±0.3μs       4.42±0.1μs     0.55  tslibs.timedelta.TimedeltaConstructor.time_from_string
-     2.80±0.03μs         758±40ns     0.27  tslibs.timedelta.TimedeltaConstructor.time_from_missing
-      6.88±0.3μs       1.67±0.2μs     0.24  tslibs.timedelta.TimedeltaConstructor.time_from_int
```

I've left out all the test suite updates from #46936, save for those changes associated with `s/OverflowError/OutOfBoundsTimedelta`.

/cc @jbrockmendel @jreback","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47004/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47004/timeline,
16,https://api.github.com/repos/pandas-dev/pandas/issues/47003,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47003/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47003/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47003/events,https://github.com/pandas-dev/pandas/issues/47003,1233120596,I_kwDOAA0YD85Jf-1U,47003,ewm check for mutually exclusive arguments doesn't work when times argument is present,"{'login': 'trimcrae', 'id': 22642433, 'node_id': 'MDQ6VXNlcjIyNjQyNDMz', 'avatar_url': 'https://avatars.githubusercontent.com/u/22642433?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/trimcrae', 'html_url': 'https://github.com/trimcrae', 'followers_url': 'https://api.github.com/users/trimcrae/followers', 'following_url': 'https://api.github.com/users/trimcrae/following{/other_user}', 'gists_url': 'https://api.github.com/users/trimcrae/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/trimcrae/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/trimcrae/subscriptions', 'organizations_url': 'https://api.github.com/users/trimcrae/orgs', 'repos_url': 'https://api.github.com/users/trimcrae/repos', 'events_url': 'https://api.github.com/users/trimcrae/events{/privacy}', 'received_events_url': 'https://api.github.com/users/trimcrae/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],,3,2022-05-11T19:59:31Z,2022-05-15T01:39:17Z,,NONE,,,,"https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ewm.html ewm is supposed to accept only one of com, span, halflife and alpha and throw a ValueError if multiple are submitted at once. However, when `times`  is input as an argument, this check is bypassed.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47003/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47003/timeline,
17,https://api.github.com/repos/pandas-dev/pandas/issues/46999,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46999/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46999/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46999/events,https://github.com/pandas-dev/pandas/issues/46999,1232815561,I_kwDOAA0YD85Je0XJ,46999,"BUG: Allow using datetime64[ns, UTC] in IntervalDtype","{'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4NDA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries', 'name': 'Timeseries', 'color': 'AFEEEE', 'default': False, 'description': None}, {'id': 150096370, 'node_id': 'MDU6TGFiZWwxNTAwOTYzNzA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Interval', 'name': 'Interval', 'color': '009800', 'default': False, 'description': 'Interval data type'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 996, 'closed_issues': 843, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-05-16T15:43:21Z', 'due_on': None, 'closed_at': None}",0,2022-05-11T15:14:09Z,2022-05-11T15:14:09Z,,MEMBER,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
dates = pd.date_range(""2022"", periods=3, tz=""UTC"")
print(pd.IntervalIndex.from_arrays(dates[:-1], dates[1:]))
print(
    pd.IntervalIndex.from_arrays(
        [""2022-01-01"", ""2022-01-02""],
        [""2022-01-02"", ""2022-01-03""],
        dtype=""interval[datetime64[ns, UTC], right]"",
    )
)
```


### Issue Description

raises `TypeError: data type 'interval[datetime64[ns, UTC], right]' not understood`

xref #46666

works for Interval of naive timeseries...

```
dates = pd.date_range(""2022"", periods=3)
print(pd.IntervalIndex.from_arrays(dates[:-1], dates[1:]))
print(
    pd.IntervalIndex.from_arrays(
        [""2022-01-01"", ""2022-01-02""],
        [""2022-01-02"", ""2022-01-03""],
        dtype=""interval[datetime64[ns], right]"",
    )
)
```

### Expected Behavior

```
IntervalIndex([(2022-01-01, 2022-01-02], (2022-01-02, 2022-01-03]], dtype='interval[datetime64[ns, UTC], right]')
```

### Installed Versions

.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46999/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46999/timeline,
18,https://api.github.com/repos/pandas-dev/pandas/issues/46998,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46998/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46998/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46998/events,https://github.com/pandas-dev/pandas/issues/46998,1232753138,I_kwDOAA0YD85JelHy,46998,ENH: Allow storing timezone-aware datetimes in a series with a datetime64 dtype,"{'login': 'thehomebrewnerd', 'id': 4307001, 'node_id': 'MDQ6VXNlcjQzMDcwMDE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4307001?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/thehomebrewnerd', 'html_url': 'https://github.com/thehomebrewnerd', 'followers_url': 'https://api.github.com/users/thehomebrewnerd/followers', 'following_url': 'https://api.github.com/users/thehomebrewnerd/following{/other_user}', 'gists_url': 'https://api.github.com/users/thehomebrewnerd/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/thehomebrewnerd/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/thehomebrewnerd/subscriptions', 'organizations_url': 'https://api.github.com/users/thehomebrewnerd/orgs', 'repos_url': 'https://api.github.com/users/thehomebrewnerd/repos', 'events_url': 'https://api.github.com/users/thehomebrewnerd/events{/privacy}', 'received_events_url': 'https://api.github.com/users/thehomebrewnerd/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 60458168, 'node_id': 'MDU6TGFiZWw2MDQ1ODE2OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timezones', 'name': 'Timezones', 'color': '5319e7', 'default': False, 'description': 'Timezone data dtype'}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 996, 'closed_issues': 843, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-05-16T15:43:21Z', 'due_on': None, 'closed_at': None}",2,2022-05-11T14:34:42Z,2022-05-16T00:13:10Z,,NONE,,,,"#### Is your feature request related to a problem?

I wish I could use pandas to store a column of timezone-aware datetime values with different timezones in a series with a `datetime64` dtype. In certain applications it is desirable to perform operations on all columns of a certain type, and currently a column with mixed types gets stored as `object` which makes it difficult to programmatically identify the column as containing datetime values based on the dtype and the `object` dtype prevents doing things like accessing the day of the datetime with the `.dt` accessor.

#### Describe the solution you'd like

I would like to have the ability to store a series of timezone aware values with mixed timezones and use the `.dt` accessor to access the underlying datetime components:

```
mixed_tz_series = pd.Series([
    pd.to_datetime(""2018-03-01"").tz_localize(tz=""US/Pacific""),
    pd.to_datetime(""2018-03-01"").tz_localize(tz=""US/Central""),
    pd.to_datetime(""2018-03-01"").tz_localize(tz=""Europe/Vienna""),
], dtype=""datetime64[ns]"")

mixed_tz_series.dt.day
```

#### API breaking implications

None that I'm aware of.

#### Describe alternatives you've considered

Instead of using the `.dt` accessor on the series, one could use `apply` with a lambda function (or other function) to get at the underlying date components, but this does not address the fact that the series is not stored with a `datetime` dtype, making it more difficult to determine that the datetime operations could/should be applied to the column.

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46998/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46998/timeline,
19,https://api.github.com/repos/pandas-dev/pandas/issues/46997,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46997/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46997/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46997/events,https://github.com/pandas-dev/pandas/issues/46997,1232414068,I_kwDOAA0YD85JdSV0,46997,BUG: read_csv(index_col=False) -> auto-generated column headers for variable row length get headers of type int,"{'login': 'arekkulczycki', 'id': 36327192, 'node_id': 'MDQ6VXNlcjM2MzI3MTky', 'avatar_url': 'https://avatars.githubusercontent.com/u/36327192?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/arekkulczycki', 'html_url': 'https://github.com/arekkulczycki', 'followers_url': 'https://api.github.com/users/arekkulczycki/followers', 'following_url': 'https://api.github.com/users/arekkulczycki/following{/other_user}', 'gists_url': 'https://api.github.com/users/arekkulczycki/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/arekkulczycki/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/arekkulczycki/subscriptions', 'organizations_url': 'https://api.github.com/users/arekkulczycki/orgs', 'repos_url': 'https://api.github.com/users/arekkulczycki/repos', 'events_url': 'https://api.github.com/users/arekkulczycki/events{/privacy}', 'received_events_url': 'https://api.github.com/users/arekkulczycki/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-05-11T10:40:31Z,2022-05-12T10:30:33Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
from io import StringIO

csv = ""1,2\n1,2,3""
io = StringIO()
io.write(csv)
io.seek(0)
usecols = lambda header: print(type(header))
pd.read_csv(io, index_col=False, usecols=usecols)

# (..)
# <class 'int'>
```


### Issue Description

When using `index_col=False` kwarg for `read_csv` then the number of columns read in is equal to the length of the longest row.

In such scenario, the columns which miss headers get names based on their position, but are assigned integers instead of strings. I think headers should rather be strings in general, but specifically this became a problem when I also used:
`usecols=lambda header: header.strip() in headers`
and it raised AttributeError.

### Expected Behavior

The auto-generated column name/header is a string.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-89-generic
Version          : #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : pl_PL.UTF-8
LOCALE           : pl_PL.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 1.1.0
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46997/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46997/timeline,
20,https://api.github.com/repos/pandas-dev/pandas/issues/46996,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46996/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46996/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46996/events,https://github.com/pandas-dev/pandas/issues/46996,1232171797,I_kwDOAA0YD85JcXMV,46996,BUG: pandas date_range does not work with start/end having timezone information,"{'login': 'chris-hermans', 'id': 37574849, 'node_id': 'MDQ6VXNlcjM3NTc0ODQ5', 'avatar_url': 'https://avatars.githubusercontent.com/u/37574849?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/chris-hermans', 'html_url': 'https://github.com/chris-hermans', 'followers_url': 'https://api.github.com/users/chris-hermans/followers', 'following_url': 'https://api.github.com/users/chris-hermans/following{/other_user}', 'gists_url': 'https://api.github.com/users/chris-hermans/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/chris-hermans/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/chris-hermans/subscriptions', 'organizations_url': 'https://api.github.com/users/chris-hermans/orgs', 'repos_url': 'https://api.github.com/users/chris-hermans/repos', 'events_url': 'https://api.github.com/users/chris-hermans/events{/privacy}', 'received_events_url': 'https://api.github.com/users/chris-hermans/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 60458168, 'node_id': 'MDU6TGFiZWw2MDQ1ODE2OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timezones', 'name': 'Timezones', 'color': '5319e7', 'default': False, 'description': 'Timezone data dtype'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-05-11T08:00:51Z,2022-05-11T17:24:48Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

print(""Unexpected range:"")
print(pd.date_range(start=dt.datetime(2020, 1, 1, 0, 0, 0, tzinfo=pytz.timezone(""Europe/Kiev"")),
                    end=dt.datetime(2020, 1, 1, 20, 0, 0, tzinfo=pytz.timezone(""Europe/Kiev"")),
                    freq=""1H"", closed=""left""))
```


### Issue Description

Providing the start and end arguments in the pandas date_range function as time-aware timestamps will not result in the expected behavior. Some additional minutes (not only hours) are added/subtracted from the provided start/end points, depending on the provided time-zone.

Providing time-naive start and end arguments with the timezone information provided separately in the tz argument works as expected.

### Expected Behavior

```
print(""Expected range:"")
print(pd.date_range(start=dt.datetime(2020, 1, 1, 0, 0, 0),
                    end=dt.datetime(2020, 1, 1, 20, 0, 0),
                    tz=pytz.timezone(""Europe/Kiev""),
                    freq=""1H"", closed=""left""))
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Belgium.1252
pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46996/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46996/timeline,
21,https://api.github.com/repos/pandas-dev/pandas/issues/46994,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46994/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46994/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46994/events,https://github.com/pandas-dev/pandas/pull/46994,1232061638,PR_kwDOAA0YD843n4FC,46994,ENH: do not sort resulting columns when sort=False,"{'login': 'ShawnZhong', 'id': 6421097, 'node_id': 'MDQ6VXNlcjY0MjEwOTc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6421097?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ShawnZhong', 'html_url': 'https://github.com/ShawnZhong', 'followers_url': 'https://api.github.com/users/ShawnZhong/followers', 'following_url': 'https://api.github.com/users/ShawnZhong/following{/other_user}', 'gists_url': 'https://api.github.com/users/ShawnZhong/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ShawnZhong/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ShawnZhong/subscriptions', 'organizations_url': 'https://api.github.com/users/ShawnZhong/orgs', 'repos_url': 'https://api.github.com/users/ShawnZhong/repos', 'events_url': 'https://api.github.com/users/ShawnZhong/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ShawnZhong/received_events', 'type': 'User', 'site_admin': False}","[{'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 81, 'closed_issues': 764, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-05-16T14:42:35Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",3,2022-05-11T06:10:41Z,2022-05-15T18:21:51Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46994', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46994', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46994.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46994.patch', 'merged_at': None}","- [x] closes #17041
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Currently, `pivot_table` sorts the resulting columns even when `sort=False`. For example, the following code snippet produces the column [""age"", ""height""] in alphabetical order instead of the order in the original `df` or passed by `values=`. 

```py
import pandas as pd

df = pd.DataFrame(
    {
        ""firstname"": [""John"", ""Michael""],
        ""lastname"": [""Foo"", ""Bar""],
        ""height"": [173, 182],
        ""age"": [47, 33],
    }
)
result = df.pivot_table(index=[""lastname"", ""firstname""], values=[""height"", ""age""], sort=False)
print(result)
```

```
                    age  height
lastname firstname             
Foo      John        47     173
Bar      Michael     33     182
```

This PR fixes this issue by not sorting the resulting columns when `sort=False`

FYI, #17041 has some discussion about the order of the columns. PR #40954 added the keyword `sort` to `pivot_table` and was merged in v1.3. ","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46994/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46994/timeline,
22,https://api.github.com/repos/pandas-dev/pandas/issues/46993,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46993/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46993/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46993/events,https://github.com/pandas-dev/pandas/pull/46993,1231883357,PR_kwDOAA0YD843nSf9,46993,CLN: DatetimeTZBlock don't override values_for_json,"{'login': 'lithomas1', 'id': 47963215, 'node_id': 'MDQ6VXNlcjQ3OTYzMjE1', 'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lithomas1', 'html_url': 'https://github.com/lithomas1', 'followers_url': 'https://api.github.com/users/lithomas1/followers', 'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}', 'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions', 'organizations_url': 'https://api.github.com/users/lithomas1/orgs', 'repos_url': 'https://api.github.com/users/lithomas1/repos', 'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lithomas1/received_events', 'type': 'User', 'site_admin': False}","[{'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3OTI1OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20JSON', 'name': 'IO JSON', 'color': '207de5', 'default': False, 'description': 'read_json, to_json, json_normalize'}, {'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean', 'name': 'Clean', 'color': '207de5', 'default': False, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 81, 'closed_issues': 764, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-05-16T14:42:35Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",1,2022-05-11T01:27:21Z,2022-05-11T21:38:09Z,,MEMBER,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46993', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46993', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46993.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46993.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46993/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46993/timeline,
23,https://api.github.com/repos/pandas-dev/pandas/issues/46989,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46989/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46989/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46989/events,https://github.com/pandas-dev/pandas/issues/46989,1231667186,I_kwDOAA0YD85Jab_y,46989,ENH: `pd.DataFrame.groupby().sample()` to support groups with `n` smaller than group size when `replaec=False`,"{'login': 'zhangyilun', 'id': 8699465, 'node_id': 'MDQ6VXNlcjg2OTk0NjU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8699465?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zhangyilun', 'html_url': 'https://github.com/zhangyilun', 'followers_url': 'https://api.github.com/users/zhangyilun/followers', 'following_url': 'https://api.github.com/users/zhangyilun/following{/other_user}', 'gists_url': 'https://api.github.com/users/zhangyilun/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zhangyilun/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zhangyilun/subscriptions', 'organizations_url': 'https://api.github.com/users/zhangyilun/orgs', 'repos_url': 'https://api.github.com/users/zhangyilun/repos', 'events_url': 'https://api.github.com/users/zhangyilun/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zhangyilun/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-05-10T20:36:20Z,2022-05-10T20:36:20Z,,NONE,,,,"#### Is your feature request related to a problem?

Encountered issue when using `pd.DataFrame.groupby().sample()` with `replace=False`. The issue is when specified `n` is larger than some of the groups, the sampling will fail since I specified `replace=False`. Is it possible to have extra argument to allow such sampling by keeping all rows in that group if `n` is larger than group size?

#### Describe the solution you'd like

Request to have `pd.DataFrame.groupby().sample()` to allow `replace=False` when `n` larger than some of the groups and keep the entire group.

A parameter called something like `error_if_n_greater_than_group_size=True/False` to be used together with `replace=False` to handle groups smaller than specified sample size `n`.

#### API breaking implications

With default value of `True` and it will have no change to the API and return error needed. But when specified `False`, will return filtered df without error.

#### Describe alternatives you've considered

Alternatively without this option, user has to split the data into 2 parts, one df with entries that can form groups larger than the specified `n`, another with entries that can form groups smaller than the specified `n`. Run `groupby().sample()` on the first df, and combine result with second df.

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46989/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46989/timeline,
24,https://api.github.com/repos/pandas-dev/pandas/issues/46988,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46988/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46988/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46988/events,https://github.com/pandas-dev/pandas/issues/46988,1231470805,I_kwDOAA0YD85JZsDV,46988,BUG: read_excel does not convert integral floats to ints when backed by openpyxl,"{'login': 'mttr', 'id': 2159316, 'node_id': 'MDQ6VXNlcjIxNTkzMTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/2159316?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mttr', 'html_url': 'https://github.com/mttr', 'followers_url': 'https://api.github.com/users/mttr/followers', 'following_url': 'https://api.github.com/users/mttr/following{/other_user}', 'gists_url': 'https://api.github.com/users/mttr/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mttr/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mttr/subscriptions', 'organizations_url': 'https://api.github.com/users/mttr/orgs', 'repos_url': 'https://api.github.com/users/mttr/repos', 'events_url': 'https://api.github.com/users/mttr/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mttr/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1NDI3Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Excel', 'name': 'IO Excel', 'color': 'bfe5bf', 'default': False, 'description': 'read_excel, to_excel'}]",open,False,,[],,4,2022-05-10T17:24:14Z,2022-05-16T17:46:52Z,,NONE,,,,"## Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
print(pd.read_excel(""./Numbers.xlsx""))
```

sample file: [Numbers.xlsx](https://github.com/pandas-dev/pandas/files/8663691/Numbers.xlsx)

### Issue Description

Per [the documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html#pandas.read_excel) (see: convert_float), by default `read_excel` should convert any integral float into an integer. Here is the output from the above code using a simple xslx file with a single column of integers:

```
    1.0
0   2.0
1   3.0
2   4.0
3   5.0
4   6.0
5   7.0
6   8.0
7   9.0
8  10.0
9  11.0
```

As you can see, the values from that column are represented by floats instead of ints. 

This appears to be a regression (this worked as expected in 1.2.4) introduced by [this PR](https://github.com/pandas-dev/pandas/pull/39782), though it's worth noting that this was made under the belief that openpyxl did this conversion already (perhaps it did at the time- I haven't looked into it yet).

Other excel engines look to be unaffected.

### Expected Behavior

```
    1
0   2
1   3
2   4
3   5
4   6
5   7
6   8
7   9
8  10
9  11
```

### Installed Versions

```
INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.4.0
Version          : Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 22.0.4
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.24.1
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : 1.0.9
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46988/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46988/timeline,
25,https://api.github.com/repos/pandas-dev/pandas/issues/46987,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46987/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46987/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46987/events,https://github.com/pandas-dev/pandas/issues/46987,1231377166,I_kwDOAA0YD85JZVMO,46987,BUG: set_index on more than 1 column changes boolean values,"{'login': 'alonme', 'id': 25847554, 'node_id': 'MDQ6VXNlcjI1ODQ3NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/25847554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alonme', 'html_url': 'https://github.com/alonme', 'followers_url': 'https://api.github.com/users/alonme/followers', 'following_url': 'https://api.github.com/users/alonme/following{/other_user}', 'gists_url': 'https://api.github.com/users/alonme/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alonme/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alonme/subscriptions', 'organizations_url': 'https://api.github.com/users/alonme/orgs', 'repos_url': 'https://api.github.com/users/alonme/repos', 'events_url': 'https://api.github.com/users/alonme/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alonme/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5NjM5OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Algos', 'name': 'Algos', 'color': 'eb6420', 'default': False, 'description': 'Non-arithmetic algos: value_counts, factorize, sorting, isin, clip, shift, diff'}, {'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}, {'id': 1654197779, 'node_id': 'MDU6TGFiZWwxNjU0MTk3Nzc5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/hashing', 'name': 'hashing', 'color': '6beae0', 'default': False, 'description': 'hash_pandas_object'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-05-10T15:58:19Z,2022-05-15T09:39:05Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

# create df with booleans and 0,1
df = pd.DataFrame({'group_a': [1,2,1,2], 'group_b': [0,1,True,False], 'value':range(4)})

print(df)

# True and False were changed
print(df.set_index(['group_a', 'group_b']))

# Problem doesn't happen if 0/1 are not present in the column
df = pd.DataFrame({'group_a': [1,2,1,2], 'group_b': [2,3,True,False], 'value':range(4)})

print(df)

print(df.set_index(['group_a', 'group_b']))
```


### Issue Description

set_index on more than 1 column may change the values of booleans to integers/floats.

this issue only happens if (0, 0.0, 1, 1.0) are found in the same column as (True/False).

### Expected Behavior

`set_index` should not change values

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.4.0
Version          : Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.3.0
Cython           : 0.29.28
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : 1.10.6
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : 0.53.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.02.0
scipy            : 1.8.0
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46987/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46987/timeline,
26,https://api.github.com/repos/pandas-dev/pandas/issues/46986,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46986/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46986/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46986/events,https://github.com/pandas-dev/pandas/pull/46986,1231347854,PR_kwDOAA0YD843ljVf,46986,ENH: Implement nlargest and nsmallest for DataFrameGroupBy,"{'login': 'lorentzbao', 'id': 19342156, 'node_id': 'MDQ6VXNlcjE5MzQyMTU2', 'avatar_url': 'https://avatars.githubusercontent.com/u/19342156?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lorentzbao', 'html_url': 'https://github.com/lorentzbao', 'followers_url': 'https://api.github.com/users/lorentzbao/followers', 'following_url': 'https://api.github.com/users/lorentzbao/following{/other_user}', 'gists_url': 'https://api.github.com/users/lorentzbao/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lorentzbao/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lorentzbao/subscriptions', 'organizations_url': 'https://api.github.com/users/lorentzbao/orgs', 'repos_url': 'https://api.github.com/users/lorentzbao/repos', 'events_url': 'https://api.github.com/users/lorentzbao/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lorentzbao/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-05-10T15:34:59Z,2022-05-16T01:18:53Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46986', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46986', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46986.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46986.patch', 'merged_at': None}","- [ ] closes #46924 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.

Try to implement `nlargest` and `nsmallest` methods for `DataFrameGroupBy`. Appreciate any comments.

```python
>>> df
  group name  data
0   bar   b1     1
1   bar   b2     3
2   bar   b3     3
3   foo   f1     1
4   foo   f2     1
5   foo   f3     3


>>> df.groupby(""group"").nlargest(n=2)
        name  data
group
bar   1   b2     3
      2   b3     3
foo   5   f3     3
      3   f1     1


>>> df.groupby(""group"").nlargest(n=2, keep=""all"")
        name  data
group
bar   1   b2     3
      2   b3     3
foo   5   f3     3
      3   f1     1
      4   f2     1

>>> df.groupby(""group"").nsmallest(n=2)
        name  data
group
bar   0   b1     1
      1   b2     3
foo   3   f1     1
      4   f2     1


>>> df.groupby(""group"").nsmallest(n=2, keep=""all"")
        name  data
group
bar   0   b1     1
      1   b2     3
      2   b3     3
foo   3   f1     1
      4   f2     1
```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46986/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46986/timeline,
27,https://api.github.com/repos/pandas-dev/pandas/issues/46984,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46984/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46984/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46984/events,https://github.com/pandas-dev/pandas/issues/46984,1231025430,I_kwDOAA0YD85JX_UW,46984,BUG: Style.set_sticky() doesn’t work with dark mode,"{'login': 'flying-sheep', 'id': 291575, 'node_id': 'MDQ6VXNlcjI5MTU3NQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/291575?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/flying-sheep', 'html_url': 'https://github.com/flying-sheep', 'followers_url': 'https://api.github.com/users/flying-sheep/followers', 'following_url': 'https://api.github.com/users/flying-sheep/following{/other_user}', 'gists_url': 'https://api.github.com/users/flying-sheep/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/flying-sheep/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/flying-sheep/subscriptions', 'organizations_url': 'https://api.github.com/users/flying-sheep/orgs', 'repos_url': 'https://api.github.com/users/flying-sheep/repos', 'events_url': 'https://api.github.com/users/flying-sheep/events{/privacy}', 'received_events_url': 'https://api.github.com/users/flying-sheep/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 57395487, 'node_id': 'MDU6TGFiZWw1NzM5NTQ4Nw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20HTML', 'name': 'IO HTML', 'color': '006b75', 'default': False, 'description': 'read_html, to_html, Styler.apply, Styler.applymap'}, {'id': 1728592794, 'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler', 'name': 'Styler', 'color': '006b75', 'default': False, 'description': 'conditional formatting using DataFrame.style'}]",open,False,,[],,1,2022-05-10T11:39:27Z,2022-05-15T17:08:05Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

In Jupyterlab, with dark mode active:

```python
import pandas as pd

display(pd.DataFrame(dict(a=[1])).style.set_sticky())
```


### Issue Description

Calling this makes the row/column headers disappear (white text on white background)

### Expected Behavior

Background color should adapt to theme or at least foreground color should also be set

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.181-99.354.amzn2.x86_64
Version          : #1 SMP Wed Mar 2 18:50:46 UTC 2022
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 59.8.0
Cython           : None
pytest           : 7.0.0
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
fastparquet      : 0.8.1
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.4.31
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46984/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46984/timeline,
28,https://api.github.com/repos/pandas-dev/pandas/issues/46983,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46983/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46983/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46983/events,https://github.com/pandas-dev/pandas/issues/46983,1230882763,I_kwDOAA0YD85JXcfL,46983,"BUG: Setting values on a multiindex df, via loc, does nothing on 1.4.x","{'login': 'Kerybas', 'id': 42703200, 'node_id': 'MDQ6VXNlcjQyNzAzMjAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/42703200?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Kerybas', 'html_url': 'https://github.com/Kerybas', 'followers_url': 'https://api.github.com/users/Kerybas/followers', 'following_url': 'https://api.github.com/users/Kerybas/following{/other_user}', 'gists_url': 'https://api.github.com/users/Kerybas/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Kerybas/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Kerybas/subscriptions', 'organizations_url': 'https://api.github.com/users/Kerybas/orgs', 'repos_url': 'https://api.github.com/users/Kerybas/repos', 'events_url': 'https://api.github.com/users/Kerybas/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Kerybas/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 2085877452, 'node_id': 'MDU6TGFiZWwyMDg1ODc3NDUy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Copy%20/%20view%20semantics', 'name': 'Copy / view semantics', 'color': '70e5ca', 'default': False, 'description': ''}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/95', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/95', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/95/labels', 'id': 7829734, 'node_id': 'MI_kwDOAA0YD84Ad3jm', 'number': 95, 'title': '1.4.3', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 25, 'closed_issues': 45, 'state': 'open', 'created_at': '2022-04-01T18:18:24Z', 'updated_at': '2022-05-16T13:20:24Z', 'due_on': '2022-04-30T07:00:00Z', 'closed_at': None}",2,2022-05-10T09:34:20Z,2022-05-16T14:56:58Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
print(""pandas version:"", pd.__version__)

index = pd.MultiIndex.from_tuples(
    [(""A"", ""a""), (""A"", ""b""), (""A"", ""c""), (""A"", ""d""), (""B"", ""a""), (""B"", ""b"")]
)

df = pd.DataFrame(
    [[10, 100], [20, 200], [30, 300], [40, 400], [50, 500], [60, 600]],
    columns=[""val1"", ""val2""],
    index=index,
)

df.loc['A']['val1'] = 1
print(df)
```


### Issue Description

On Pandas 1.4.x (including 1.4.2), the example code does not modify df. The value `1` is not assigned.
It returns:
```
pandas version: 1.4.2
     val1  val2
A a    10   100
  b    20   200
  c    30   300
  d    40   400
B a    50   500
  b    60   600
```

(This bug could be linked to #46837)

### Expected Behavior

on Pandas 1.3.5, the example returns:  
```
pandas version: 1.3.5
     val1  val2
A a     1   100
  b     1   200
  c     1   300
  d     1   400
B a    50   500
  b    60   600
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 56.0.0
Cython           : None
pytest           : 7.1.1
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46983/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46983/timeline,
29,https://api.github.com/repos/pandas-dev/pandas/issues/46982,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46982/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46982/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46982/events,https://github.com/pandas-dev/pandas/pull/46982,1230675468,PR_kwDOAA0YD843jUMg,46982,TST: Assign back multiple column to datetime,"{'login': 'parthi-siva', 'id': 25401444, 'node_id': 'MDQ6VXNlcjI1NDAxNDQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/25401444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/parthi-siva', 'html_url': 'https://github.com/parthi-siva', 'followers_url': 'https://api.github.com/users/parthi-siva/followers', 'following_url': 'https://api.github.com/users/parthi-siva/following{/other_user}', 'gists_url': 'https://api.github.com/users/parthi-siva/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/parthi-siva/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/parthi-siva/subscriptions', 'organizations_url': 'https://api.github.com/users/parthi-siva/orgs', 'repos_url': 'https://api.github.com/users/parthi-siva/repos', 'events_url': 'https://api.github.com/users/parthi-siva/events{/privacy}', 'received_events_url': 'https://api.github.com/users/parthi-siva/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 81, 'closed_issues': 764, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-05-16T14:42:35Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",0,2022-05-10T06:24:57Z,2022-05-12T05:21:54Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46982', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46982', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46982.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46982.patch', 'merged_at': None}","This tests make sure when converting multiple columns to datetimes
and when assiging back it remains as datetime not as unix date
as mentioned in GH #20511.

- [x] closes #20511
- [x] [Tests added and passed]
- [x] All [code checks passed]
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46982/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46982/timeline,
